### ISSUE TITLE
RAG application Help

### ISSUE THREAD

**Issue by davidmonterocrespo24** [aisbroker/flexi-rag#1]
Hi, my name is David. I saw a RAG application that you are contributing and I wanted to ask if you could contact me to help me with one that I am building very similar to that one.
This is my email [davidmonterocrespo24@gmail.com](mailto:davidmonterocrespo24@gmail.com).

I look forward to your prompt response.

Regards

**Comment by hapkecom** [comment]
Hi David ... please send me more details (e.g. your GitHub-Repo-Link) ... then I can try ... Chris (at) aisbreaker.org ...
